-- Step 4: Snowflake schema for historical environmental data.
-- Applied by `python -m warehouse.setup_db`. Needs a role that can create
-- warehouses, databases and roles (ACCOUNTADMIN on a trial account works).

CREATE WAREHOUSE IF NOT EXISTS ECUERY_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ECUERY;

CREATE SCHEMA IF NOT EXISTS ECUERY.HISTORY;

-- 4a: one row per day, location and metric (years of readings)
CREATE TABLE IF NOT EXISTS ECUERY.HISTORY.DAILY_READINGS (
    DAY        DATE    NOT NULL,
    LOCATION   VARCHAR NOT NULL,
    METRIC     VARCHAR NOT NULL,
    UNIT       VARCHAR NOT NULL,
    AVG_VALUE  FLOAT   NOT NULL,
    MIN_VALUE  FLOAT   NOT NULL,
    MAX_VALUE  FLOAT   NOT NULL,
    SAMPLES    INTEGER NOT NULL,
    SOURCE     VARCHAR NOT NULL
);

CREATE OR REPLACE VIEW ECUERY.HISTORY.MONTHLY_READINGS AS
SELECT DATE_TRUNC('month', DAY) AS MONTH, LOCATION, METRIC, UNIT,
       AVG(AVG_VALUE) AS AVG_VALUE, MIN(MIN_VALUE) AS MIN_VALUE,
       MAX(MAX_VALUE) AS MAX_VALUE, SUM(SAMPLES) AS SAMPLES
FROM ECUERY.HISTORY.DAILY_READINGS
GROUP BY 1, 2, 3, 4;

-- Read-only role used for Gemini-generated SQL: Snowflake itself refuses writes.
CREATE ROLE IF NOT EXISTS ECUERY_READER;

GRANT USAGE ON WAREHOUSE ECUERY_WH TO ROLE ECUERY_READER;

GRANT USAGE ON DATABASE ECUERY TO ROLE ECUERY_READER;

GRANT USAGE ON SCHEMA ECUERY.HISTORY TO ROLE ECUERY_READER;

GRANT SELECT ON ALL TABLES IN SCHEMA ECUERY.HISTORY TO ROLE ECUERY_READER;

GRANT SELECT ON ALL VIEWS IN SCHEMA ECUERY.HISTORY TO ROLE ECUERY_READER;
