// Notable historical events shown on the landing globe. Figures are
// approximate; swap for live feeds (NOAA NHC, NIFC, OpenAQ) once the backend exists.

export type EventType = "cyclone" | "tornado" | "wildfire" | "flood" | "earthquake" | "air";

export const eventTypes: Record<
  EventType,
  { label: string; singular: string; color: string; rgb: string }
> = {
  cyclone: { label: "Hurricanes & storms", singular: "Storm", color: "#7dd3fc", rgb: "125, 211, 252" },
  tornado: { label: "Tornadoes", singular: "Tornado", color: "#c084fc", rgb: "192, 132, 252" },
  wildfire: { label: "Wildfires", singular: "Wildfire", color: "#fb923c", rgb: "251, 146, 60" },
  flood: { label: "Floods", singular: "Flood", color: "#2dd4bf", rgb: "45, 212, 191" },
  earthquake: { label: "Earthquakes", singular: "Earthquake", color: "#fb7185", rgb: "251, 113, 133" },
  air: { label: "Air quality & dust", singular: "Air quality", color: "#facc15", rgb: "250, 204, 21" },
};

export type EnvEvent = {
  id: string;
  type: EventType;
  name: string;
  place: string;
  date: string;
  lat: number;
  lng: number;
  stat: string;
  summary: string;
  question: string;
};

export const envEvents: EnvEvent[] = [
  {
    id: "milton-2024",
    type: "cyclone",
    name: "Hurricane Milton",
    place: "Gulf of Mexico → Florida",
    date: "Oct 2024",
    lat: 24.5,
    lng: -86,
    stat: "~180 mph peak winds",
    summary: "Exploded to Category 5 over the Gulf before landfall near Siesta Key.",
    question: "How fast did Hurricane Milton intensify?",
  },
  {
    id: "otis-2023",
    type: "cyclone",
    name: "Hurricane Otis",
    place: "Acapulco, Mexico",
    date: "Oct 2023",
    lat: 16.8,
    lng: -99.9,
    stat: "Tropical storm → Cat 5 in about a day",
    summary: "One of the fastest intensifications on record, catching forecasts off guard.",
    question: "Which hurricanes intensified fastest in the last decade?",
  },
  {
    id: "haiyan-2013",
    type: "cyclone",
    name: "Typhoon Haiyan",
    place: "Philippines",
    date: "Nov 2013",
    lat: 11.2,
    lng: 125,
    stat: "Among the strongest landfalls ever recorded",
    summary: "Storm surge devastated Tacloban and much of the Eastern Visayas.",
    question: "How have Western Pacific typhoon intensities changed since 1980?",
  },
  {
    id: "freddy-2023",
    type: "cyclone",
    name: "Cyclone Freddy",
    place: "Mozambique & Malawi",
    date: "Feb–Mar 2023",
    lat: -17.9,
    lng: 37,
    stat: "Longest-lived tropical cyclone on record",
    summary: "Crossed the entire southern Indian Ocean and made landfall twice.",
    question: "How long do tropical cyclones last in the Indian Ocean on average?",
  },
  {
    id: "rolling-fork-2023",
    type: "tornado",
    name: "Rolling Fork tornado",
    place: "Mississippi, USA",
    date: "Mar 2023",
    lat: 32.9,
    lng: -90.9,
    stat: "EF4",
    summary: "A long-track nighttime tornado through the Mississippi Delta.",
    question: "How many EF4+ tornadoes hit the US each year since 2000?",
  },
  {
    id: "moore-2013",
    type: "tornado",
    name: "Moore tornado",
    place: "Oklahoma, USA",
    date: "May 2013",
    lat: 35.3,
    lng: -97.5,
    stat: "EF5",
    summary: "Struck the same city hit by an F5 in 1999.",
    question: "Is Tornado Alley shifting east?",
  },
  {
    id: "canada-2023",
    type: "wildfire",
    name: "Canada wildfire season",
    place: "Québec & across Canada",
    date: "2023",
    lat: 50.5,
    lng: -75.5,
    stat: "~17M hectares burned",
    summary: "Canada's worst season on record; smoke reached New York and Europe.",
    question: "Compare 2023 vs 2024 wildfire acreage in Canada",
  },
  {
    id: "lahaina-2023",
    type: "wildfire",
    name: "Lahaina fire",
    place: "Maui, Hawaii",
    date: "Aug 2023",
    lat: 20.9,
    lng: -156.7,
    stat: "Deadliest US wildfire in over a century",
    summary: "Wind-driven fire destroyed most of the historic town of Lahaina.",
    question: "How has drought in Hawaii changed over the last 30 years?",
  },
  {
    id: "black-summer-2019",
    type: "wildfire",
    name: "Black Summer",
    place: "New South Wales, Australia",
    date: "2019–20",
    lat: -35.7,
    lng: 150,
    stat: "Over 17M hectares burned",
    summary: "Months of fires across southeastern Australia after record heat and drought.",
    question: "Hottest year on record in Australia",
  },
  {
    id: "delhi-2024",
    type: "air",
    name: "Delhi smog",
    place: "New Delhi, India",
    date: "Nov 2024",
    lat: 28.6,
    lng: 77.2,
    stat: "Daily AQI near 500 (\"severe\")",
    summary: "Crop burning, traffic and still winter air trapped pollution over the city.",
    question: "What was the AQI in Delhi last November?",
  },
  // ---- Europe ----
  {
    id: "ophelia-2017",
    type: "cyclone",
    name: "Ex-Hurricane Ophelia",
    place: "Ireland & UK",
    date: "Oct 2017",
    lat: 51.9,
    lng: -9.5,
    stat: "Easternmost major Atlantic hurricane on record",
    summary: "Hit Ireland as a powerful post-tropical storm, and pulled in Saharan dust and Iberian wildfire smoke that turned the sun red over England.",
    question: "How often do ex-hurricanes reach the UK and Ireland?",
  },
  {
    id: "eunice-2022",
    type: "cyclone",
    name: "Storm Eunice",
    place: "Southern England",
    date: "Feb 2022",
    lat: 50.7,
    lng: -1.6,
    stat: "122 mph gust, an England record",
    summary: "One of the strongest windstorms to hit southern Britain in decades; millions lost power.",
    question: "Are UK winters getting wetter since 1950?",
  },
  {
    id: "moravia-2021",
    type: "tornado",
    name: "South Moravia tornado",
    place: "Czechia",
    date: "Jun 2021",
    lat: 48.85,
    lng: 17.1,
    stat: "IF4, the strongest in modern Czech records",
    summary: "Tore through villages near Hodonín, a rare violent tornado for central Europe.",
    question: "How has extreme daily rainfall in Czechia changed since 1950?",
  },
  {
    id: "evros-2023",
    type: "wildfire",
    name: "Evros wildfire",
    place: "Northeastern Greece",
    date: "Aug 2023",
    lat: 40.95,
    lng: 25.9,
    stat: "Largest wildfire recorded in the EU",
    summary: "Burned for weeks near Alexandroupolis during one of Greece's worst fire seasons.",
    question: "How has burned area in Mediterranean Europe changed since 2000?",
  },
  {
    id: "valencia-2024",
    type: "flood",
    name: "Valencia floods",
    place: "Valencia, Spain",
    date: "Oct 2024",
    lat: 39.4,
    lng: -0.4,
    stat: "More than 200 deaths",
    summary: "A stalled storm system (DANA) dumped months of rain in hours on the Valencia region.",
    question: "How has extreme daily rainfall in Spain changed since 1950?",
  },
  // ---- North Africa & Middle East ----
  {
    id: "saharan-dust-2022",
    type: "air",
    name: "Saharan dust outbreak",
    place: "Sahara → Spain",
    date: "Mar 2022",
    lat: 32,
    lng: -1,
    stat: "Skies turned orange across Spain",
    summary: "A storm lifted desert dust over North Africa and carried it deep into Europe.",
    question: "How often does Saharan dust reach Europe each year?",
  },
  {
    id: "godzilla-dust-2020",
    type: "air",
    name: "\"Godzilla\" dust plume",
    place: "West Africa → Caribbean",
    date: "Jun 2020",
    lat: 19.5,
    lng: -16,
    stat: "Densest Saharan plume in decades",
    summary: "A vast dust cloud crossed the Atlantic and hazed skies from the Caribbean to Texas.",
    question: "How much Saharan dust crosses the Atlantic each summer?",
  },
  {
    id: "bodele",
    type: "air",
    name: "Bodélé Depression",
    place: "Chad",
    date: "Year-round",
    lat: 17,
    lng: 18,
    stat: "Earth's largest single source of dust",
    summary: "A dry ancient lakebed whose dust storms feed air across Africa and fertilize the Amazon.",
    question: "Where do the world's biggest dust storms come from?",
  },
  {
    id: "derna-2023",
    type: "flood",
    name: "Derna dam collapse",
    place: "Derna, Libya",
    date: "Sep 2023",
    lat: 32.8,
    lng: 22.6,
    stat: "Two dams burst after Storm Daniel",
    summary: "Floodwater swept through the city after a Mediterranean storm's extreme rainfall.",
    question: "How much rain did Storm Daniel bring to Libya?",
  },
  {
    id: "morocco-2023",
    type: "earthquake",
    name: "Al Haouz earthquake",
    place: "High Atlas, Morocco",
    date: "Sep 2023",
    lat: 31.1,
    lng: -8.4,
    stat: "M6.8",
    summary: "Devastated mountain villages south of Marrakesh; Morocco's deadliest quake in decades.",
    question: "How often do M6+ earthquakes strike North Africa?",
  },
  {
    id: "turkey-syria-2023",
    type: "earthquake",
    name: "Türkiye–Syria earthquake",
    place: "Southern Türkiye & Syria",
    date: "Feb 2023",
    lat: 37.2,
    lng: 37,
    stat: "M7.8 · over 50,000 deaths",
    summary: "Two major quakes hours apart collapsed buildings across a vast region.",
    question: "What were the deadliest earthquakes of the last 25 years?",
  },
  // ---- Asia ----
  {
    id: "pakistan-2022",
    type: "flood",
    name: "Pakistan monsoon floods",
    place: "Sindh, Pakistan",
    date: "Jun–Sep 2022",
    lat: 26.5,
    lng: 68.5,
    stat: "About a third of the country flooded",
    summary: "Record monsoon rain and glacial melt left millions displaced.",
    question: "How has monsoon rainfall in Pakistan changed since 1960?",
  },
  {
    id: "sylhet-2022",
    type: "flood",
    name: "Sylhet floods",
    place: "Sylhet, Bangladesh",
    date: "Jun 2022",
    lat: 24.9,
    lng: 91.9,
    stat: "Millions stranded by monsoon floods",
    summary: "Heavy rain upstream in India sent rivers over their banks across northeastern Bangladesh.",
    question: "How has monsoon flooding in Bangladesh changed since 2000?",
  },
  {
    id: "myanmar-2025",
    type: "earthquake",
    name: "Myanmar earthquake",
    place: "Sagaing / Mandalay, Myanmar",
    date: "Mar 2025",
    lat: 22,
    lng: 95.9,
    stat: "M7.7 · felt as far as Bangkok",
    summary: "Ruptured the Sagaing Fault near Mandalay, Myanmar's second-largest city.",
    question: "How many M7+ earthquakes happen worldwide each year?",
  },
  {
    id: "noto-2024",
    type: "earthquake",
    name: "Noto earthquake",
    place: "Ishikawa, Japan",
    date: "Jan 2024",
    lat: 37.5,
    lng: 137.2,
    stat: "M7.5 on New Year's Day",
    summary: "Uplifted parts of the coastline and triggered tsunami warnings along the Sea of Japan.",
    question: "How often does Japan have M7+ earthquakes?",
  },
  {
    id: "yakutia-2021",
    type: "wildfire",
    name: "Yakutia wildfires",
    place: "Siberia, Russia",
    date: "Summer 2021",
    lat: 63,
    lng: 129,
    stat: "Smoke reached the North Pole",
    summary: "Fires across the Siberian taiga during an unusually hot, dry summer.",
    question: "How has wildfire activity in the Arctic changed since 2000?",
  },
  // ---- South America ----
  {
    id: "pantanal-2020",
    type: "wildfire",
    name: "Pantanal fires",
    place: "Brazil",
    date: "2020",
    lat: -17.5,
    lng: -57.4,
    stat: "Nearly a third of the wetland burned",
    summary: "Drought turned the world's largest tropical wetland into a tinderbox.",
    question: "How has drought in the Pantanal changed over the last 20 years?",
  },
  {
    id: "chile-2010",
    type: "earthquake",
    name: "Maule earthquake",
    place: "Central Chile",
    date: "Feb 2010",
    lat: -36.1,
    lng: -72.9,
    stat: "M8.8, among the largest ever recorded",
    summary: "Triggered a Pacific-wide tsunami and shifted the city of Concepción several meters west.",
    question: "What are the largest earthquakes ever recorded?",
  },
];
